name: yet_another_state_holder
description: Yet another state holder.
version: 0.5.2
repository: https://github.com/martinsellergren/yet_another_state_holder

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.0.0

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.25.6
