name: yet_another_state_holder
description: Yet another state holder.
version: 0.5.0
repository: https://github.com/martinsellergren/yet_another_state_holder

environment:
  sdk: ^3.9.0

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.25.6
